### ISSUE TITLE
Add Christopher Olah's Visual Information Theory guide to Optional Reading section of InfoGAN#1-information-theory

### ISSUE THREAD

**Issue by hemildesai** [depthfirstlearning/depthfirstlearning.com#10]
The link for the resource is https://colah.github.io/posts/2015-09-Visual-Information/

I found this article a great resource for introduction to Information Theory, and it might be helpful to have as many resources as possible available optionally for the in-depth style.

**Comment by cinjon** [comment]
Sure, can you file a pull request for this?

**Comment by hemildesai** [comment]
Yes, will do!
