### ISSUE TITLE
Additional materials/posts related to some of the common papers.

### ISSUE THREAD

**Issue by MrinalJain17** [depthfirstlearning/depthfirstlearning.com#12]
This looks like a great initiative, and it's something that was much needed.

But if you could also add the explanation/resources of some of the 'elementary' research papers (and by *elementary* I do not mean simple - rather the basic/foundation), like papers introducing CNNs or RNNs, or some regularization technique like dropout, it would be really helpful. 

The reason for this is that if you have to learn about GAN (say a specific use-case of GAN like neural-style transfer), it's necessary that you should have the required knowledge regarding CNNs.

Although I know that explaining each and every paper out there in the domain of ML is not plausible, but maybe this could be done for some of the *foundational* papers.

**Comment by cinjon** [comment]
By foundational, are you referring to the initial papers that we are seeding this with or are you thinking of foundational in terms of, say, Ian Goodfellow's paper on GANs or Alex Krizhevsky's ImageNet paper?

**Comment by MrinalJain17** [comment]
Yes... By foundational I mean papers like Ian Goodfellow's paper on GANs (or others such).

**Comment by cinjon** [comment]
Ok, so I think what you're asking is for us to do curricula for those foundational papers? If so, that sounds like a wonderful contribution 🥇. Are you interested in doing that?

**Comment by MrinalJain17** [comment]
I would love to contribute. As of now, I am still working on my understanding of neural networks (a more apt way to say this would probably be that I am still learning), and as soon as I come up with something that's good enough to be a part of this repository (by aligning with the ideology of *depthfirstlearning* and also being technically accurate), I'll actively contribute.

**Comment by suryabhupa** [comment]
Another perspective I have on depthfirstlearning is that it's helping to bring more educational material to modern research papers that don't yet have comprehensive guides to understanding them yet. 

CNNs, RNNs, and GANs might already have guides that many people have written, but something like neural style transfer might be a good candidate for understanding it and its follow up papers well. If you have other papers that you'd like to see, let us know, or feel free to start building them yourself. :)

Best of luck with your studies!

**Comment by cinjon** [comment]
Going to close this for now, but please do come and talk to us when if you would like to contribute!
