### ISSUE TITLE
Typos in "About" page

### ISSUE THREAD

**Issue by jenkspt** [depthfirstlearning/depthfirstlearning.com#15]
[http://www.depthfirstlearning.com/about/](http://www.depthfirstlearning.com/about/)
Typo 1:
Second paragraph, third sentence, extraneous "is".
"We spent some time understanding each paper and writing down the core concepts on which they were **is** built."

Typo 2:
Fourth paragraph, fourth sentence, duplicate "out".
"Check out **out** github for examples and open an issue detailing which paper you want to study."

**Comment by cinjon** [comment]
Thanks! (fixed)
