### ISSUE TITLE
Small link issues

### ISSUE THREAD

**Issue by chisness** [depthfirstlearning/depthfirstlearning.com#24]
http://www.depthfirstlearning.com/2018/DeepStack
Noam Brown's same video is the 2nd optional reading in Part 1 and also the 2nd optional reading in Part 6

http://www.depthfirstlearning.com/2018/AlphaGoZero
Optional readings 3 and 4 in Part 1 are dead links. 
Working links are respectively: https://www.chessprogramming.org/index.php?title=Minimax, https://www.chessprogramming.org/Alpha-Beta

**Comment by cinjon** [comment]
Thanks for the heads up! Do you mind submitting a PR for it?

**Comment by chisness** [comment]
Submitted

**Comment by chisness** [comment]
The first link in the [AlphaGo](http://www.depthfirstlearning.com/2018/AlphaGoZero) DFL seems to be dead 

Required Reading: Cornell Recitation on Minimax & AB Pruning.
https://www.cs.cornell.edu/courses/cs312/2002sp/lectures/rec21.htm

A recent Cornell lecture I found on minimax that could be a replacement: http://www.cs.cornell.edu/courses/cs4700/2019sp/lectures/Lecture9.pdf

**Comment by cinjon** [comment]
Looks reasonable. Mind submitting a PR?

**Comment by chisness** [comment]
Done!
