### ISSUE TITLE
Error in Problem Set 1 2e?

### ISSUE THREAD

**Issue by RylanSchaeffer** [depthfirstlearning/depthfirstlearning.com#39]
I think there may be an error in Problem Set 1 2e:

![image](https://user-images.githubusercontent.com/8942987/86628946-7d2bdd80-bf7f-11ea-8635-dd57dba058b1.png)

Specifically, x = phi(h), whereas the integrand term has phi(x). If this is a mistake, the problem is carried forward to 

![image](https://user-images.githubusercontent.com/8942987/86629015-9af94280-bf7f-11ea-9ee6-94e6a3eab71f.png)

**Comment by cinjon** [comment]
Thanks Rylan, which curriculum is this?

**Comment by RylanSchaeffer** [comment]
http://www.depthfirstlearning.com/2020/Resurrecting-Sigmoid

**Comment by RylanSchaeffer** [comment]
@cinjon bump?

**Comment by cinjon** [comment]
Sorry for the delay, and thanks for the bump! I'm not so familiar with this one, will ping the authors right now.

**Comment by RylanSchaeffer** [comment]
Thank you!

Cheers,
Rylan Schaeffer

**Comment by ramasesh** [comment]
Hi Ryan,
Thanks for the question!  I think I see the confusion.  Though I think the expression is still correct, we used bad notation in writing $$x$$ as the variable of integration.  In the equation with integration over $$x$$, this $$x$$ is just a dummy variable, not the same $$x$$ as $$x^{l-1}_i$$.  

Does this clear things up?   If so, we should probably change that expression to give the dummy variable a different name, maybe $$h$$.  

Cheers,
Vinay

**Comment by ramasesh** [comment]
Oh, I see.  Yeah, good question, let me try and explain.  In this notation, $$p_{h^{l-1}}(x)$$ means "the probability density function of the random variable $$h^{l-1}$$, evaluated at value $$x$$".  So $$h^{l-1}$$ is the random variable, and the probability of it taking on a value between, say, $$4$$ and $$4 + \epsilon$$ is $$p_{h^{l-1}}(4)\times\epsilon$$.  Does this help?

**Comment by RylanSchaeffer** [comment]
Yep! Thank you for clarifying!
