### ISSUE TITLE
Add curriculum for Neural Mechanics paper

### ISSUE THREAD

**Issue by ramasesh** [depthfirstlearning/depthfirstlearning.com#44]
I'd like to add a curriculum for the recent paper [Neural mechanics: symmetry and broken conservation laws in deep learning dynamics](https://arxiv.org/pdf/2012.04728.pdf).  There is a lot of depth to this paper, and the payoff (being able to calculate exact training dynamics of certain parameter combinations) makes that worth studying.  Like the Resurrecting the Sigmoid curriculum, I'd probably structure it to be mostly based around problem sets, except with more interactive (coding/jupyter notebook) problems.  If this sounds good, I can get started.

**Comment by cinjon** [comment]
That sounds amazing. How can we help?

**Comment by ramasesh** [comment]
Sorry, I missed this.  I'll submit a pull request with an outline soon, and any eyes on that would be very helpful!

**Comment by cinjon** [comment]
Sounds good!
